### ISSUE TITLE
Style sheet compile failure

### ISSUE THREAD

**Issue by zignig** [kaosat-dev/CoffeeSCad#110]
Running cake build from the root directory: 

/var/www/CoffeeSCad/Cakefile:62
            throw source + ' ' + error;
                               ^
./src/style/swatch/swatchMaker.less Error: Command failed: FileError: '../../assets/css/bootstrap/less/bootstrap.less' wasn't found.
 in /var/www/CoffeeSCad/src/style/swatch/swatchMaker.less:1:0
1 @import "../../assets/css/bootstrap/less/bootstrap.less";
2 @import "spacelab/variables.less";

running node version v0.6.19

**Comment by kaosat-dev** [comment]
that is my bad , that was an experiment, only the coffeescad style (and anything you base of off it, ie , copy the folder, rename it) will work, best to remove the swatch folder completely.
The way style sheet compilation currently works is as follows: 
-if you modified a LESS file, it will look for a file named "bootstrap.less" in the SAME folder as the modified file
- and compile that one and that one ONLY, because that is the file that has all the includes  (see the one in the coffeescad style folder for reference)
- the "bootstrap.less" file looks like this:
  
  @import "../../../assets/css/bootstrap/less/bootstrap.less";
  @import "./variables.less";
  @import "./theme.less";
  @import "../../../assets/css/bootstrap/less/utilities.less";
