### ISSUE TITLE
Add XYZ axis helper

### ISSUE THREAD

**Issue by Thav** [kaosat-dev/CoffeeSCad#150]
I little helper axis like you can see in the bottom left corner of the render window in the following screenshot ...
http://www.openscad.org/assets/img/screenshot.gif
... would be terribly helpful. As it is, I have no way of telling what axis is X and Y, and still have trouble telling at a glance what positive X and positive Y are. So then I just have to try something. This is compounded by CoffeeSCad's unintuitive (for me, at least) default orientation of X and Y, which I assume has its roots in computer graphics.

**Comment by se5a** [comment]
Try http://coffeescad.net/online_edge/# 
rather than just http://coffeescad.net/online/ 
edge has it. (edge is the latest, and possibly less stable version) 
I see what you mean about the default orientation, I never noticed that before.

**Comment by kaosat-dev** [comment]
@Thav : ditto what @se5a  said, best to use the edge version for the axis helper ( I could have swarn I updated the regular version to match that one, since the edge version is the latest, will check).
I am surprised you say the X/Y orientation is unintuitive, normally it should be facing the same way as openscad's x/y by default : do you mean the "increase" in x/y should be reversed ?

again, very willing to change things, or add an option to invert things etc

**Comment by se5a** [comment]
@Mark, when you start, +X and +Y are towards you to the left and right respectively, ie just the rotation of the view, when you first start. at least thats what I think @Thav was meaning. it'd make a little more sense if it were rotated so +Y was away from you and +X to the right. ie, Lclick mousebutton down and drag right till it rotates about ~135 degrees.

**Comment by Thav** [comment]
Ah ha! There it is in edge. The orientation of the axes are what I expected. I was just so thrown by the normal view (in the way @se5a describes), that I started making some parts swapping my x and y and just lost track of what was going on. But yes, the cross product |x| x |y| = |z|, so we're good :]

**Comment by kaosat-dev** [comment]
You are both right , I must confess that it confuses me as well sometimes:)
I could make like @se5a  describes, will give it a try to see if it seems more intuitive:à
