### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by KimGressens** [kaosat-dev/CoffeeSCad#60]
Hi,

Really like your work, cool stuff!

I checked out your dev branch and got the whole thing running, quite easily. I was looking at adding parameters (like openJSCad has) but they're currently stripped from your code.

Any thoughts on how you would define parameters in a coffeescad file? As the concept of functions (like OpenJsCad has a main and getParamsDefinitions function) doesn't seem to be there in your implementation, I'm not sure how one would add parameter definitions in the code.

One idea is splitting up the code editor with a separate 'view' that can be toggled and where parameters can be added/edited but that seems to cumbersome, no?

Looking forward to hearing your ideas :-)

**Comment by kaosat-dev** [comment]
Thanks a lot Kim !

Did you get things running with the cakeFile ? (I really need to add some dev information to the wiki)

You are completely right, currently parameters are not supported, but good that you mention it, since it is planned:)
Since Coffeescad is progressively moving away from the way OpenJsCad, I have "broken" some of the old features, while I migrate them into something cleaner..

The way I currently planned to implement it, was having a "configuration" file (as multi file support is almost added),  which would be added by default to all projects , and all parameters would be read from there, and then a separate view, like said, to display the more "user friendly" version.

I don't quite know how yet, but I would like to add an "export" system of sorts that could generate a page with the friendly UI and 3d view for easy embedding in websites etc.

If you have other ideas or mockups or suggestions , I am all ears :)

**Comment by KimGressens** [comment]
Yup, got things running with the cakeFile, wasn't that hard. Only had to install some packages via npm, so maybe it's good to add a package.json file to the repo (like in my commit https://github.com/KimGressens/CoffeeSCad/commit/27a2d6842b1fd26716eccb09fb8990ac3a9ac2c8 )

The configuration file approach seems to be a very good approach to me. How would you define parameters? With an array? (excuse my notation, I'm not that profficient in Coffeescript, I normally write Javascript)
`var parameters = [
{name: 'topdiameter', caption: 'Inner diameter of top hook:', type: 'float', default: 16.7},
{ name: 'clampfactor', caption: 'Snugness of top hook (0 - 100):', type: 'float', default: 25 }
];`

And how would you use these parameters in the code? Using a function call? Or?

The export system is indeed needed. I don't think it needs to be complicated. A simple viewer module which loads in an external file and renders the necessary controls would suffice, no?

**Comment by kaosat-dev** [comment]
Neat ! I will add a packages.json file , good move! :+1:  (or , don't hesitate to do some pull requests:)

Yeah the array is one of the possible solutions : (no problem using the javascript notation I tend to use both depending on the need, and Coffeescript understands both)
A few thoughts about the possibilites
- define a parameters array and return it at the end of the file 
- define the various attributes directly without wrapping them in a "parameters" array  ie:
  var TopDiameter = { caption:'Inner diameter of top hook:', type: 'float', default: 16.7}
  var ClampFactor = { caption:'Inner diameter of top hook:', type: 'float', default: 16.7}
  basically like you would define variables in a module

since there is already a hackish , but existing "include" method to reference other files (it will be overhauled soon to work in multi- file projects) , I though of either having a default ' include "config.coffee"' in all files, or have the file imported all the time, but be a hidden import : this means you could just reference those parameters anywhere, directly, as if they were local params.

Not too sure about the viewer module yet, the "multi file" aspect and the dependencies on backbone might make "extracting" it from the main app a bit harder than I hope, but I haven't given enough thought to it just yet.
