### ISSUE TITLE
Using the coffeescad.org domain name

### ISSUE THREAD

**Issue by ErikDeBruijn** [kaosat-dev/CoffeeSCad#67]
Hi Mark,

I'm a big fan of what you're doing with CoffeeSCAD. I'm fascinated with the concept of browser-based instant 3D modeling, it can make things much more accessible to a wider audience.

Back on topic: I've registered coffeescad.org to prevent it from being squatted. Whenever you want I can arrange that it's transfered to you. Besides transferring ownership, I think it wouldn't hurt to use the domain name coffeescad.org to actually host the live demo. Actually, I gave it a try, but apparently I'm missing some files. Get in touch at Erik - @ - Ultimaker - dot - com. I also have Jabber/GTalk under that e-mail address.

Cheers,

Erik de Bruijn
Co-Founder of Ultimaker

**Comment by ryneches** [comment]
Ha! It was only a matter of time before Erik showed up. :-)

We should get Mark and Daid together. It would be totally freaking awesome to be able to click "print" in CoffeeSCad and have Cura slice the model. Maybe a browser pluggin?

Russell

**Comment by ErikDeBruijn** [comment]
I agree. :+1: I've made a browser plugin, actually (nothing fancy, just a piece of javascript that runs as an extension in Chrome). I used it for printing directly from Thingiverse with a single click. But since it's MakerbotThingiverse now, I don't want to release it in the current state it's in. Enabling direct printing from other applications is cool though, indeed.

**Comment by kaosat-dev** [comment]
Hello @ErikDeBruijn !
Sorry for the slow reply.
Thanks a lot for the kind words, and the very good initiative for the domain name! This was on my todo list ( to host the demo on a custom domain, beginning with the upcoming, 0.3 version) but I had not gotten around to do it yet , so very nice of you to do this :)

Your post also acted as a wake up call, so I also registered coffeescad.net/ and .com so that they can all point to the same hosted files in the future.
I will get back to you asap via email so we can transfer ownership.
Btw I am curious : what kind of issue did you run into when trying to host the files ? Was it the dev branch or the gh-pages one ?

(ps, big fan of the Ultimaker! should get mine soon, if DHL does not loose the package again...)

@ryneches 
Funny you should mention that, slicing directly IN Coffeescad or via a browser plugin is one of my long term goal, so I might annoy Daid with some questions about this , when I get to that point :)

@ErikDeBruijn that sounds nifty ,  even if I completely get your reservations about the "Makerbot"Thingiverse part. Never experimented with such type of browser plugins before, really curious on how you got it working.
 If you really don't want it to be public, I'll mention it in my email to you :)

**Comment by kaosat-dev** [comment]
As the site is now released (accessible from either .com/.org/.net) I am closing this ! Thanks a lot @ErikDeBruijn ! :)
