### ISSUE TITLE
Object translation applied to original object not a copy

### ISSUE THREAD

**Issue by derrickoswald** [kaosat-dev/CoffeeSCad#79]
In the following object (a stepper motor) there is only one mounting hole.
I think it's because the translate call actually adjusts the original object and not a copy.
See the comment at the end.

shaft_len = 22
shaft_radius = 2.5
motorBody_len = 47.5

motorBody_width = 42
motorRing_radius = 11
motorRing_height = 2

mountingholes_fromcent = 15.5
mountingholes_radius = 1.5
mountingholes_depth = 4.5

motorBody = new Cube
  size: [motorBody_width, motorBody_width, motorBody_len]
  center: [-motorBody_width / 2.0, -motorBody_width / 2.0, -motorBody_len]

ring = new Cylinder
  h: motorRing_height
  r: motorRing_radius
  center: [0, 0, motorBody_len]

shaft = new Cylinder
  h: shaft_len
  r: shaft_radius
  center: [0, 0, motorBody_len + motorRing_radius]

motor = motorBody.union([ring, shaft])

mountingholes = new Cylinder
  h: -mountingholes_depth
  r: mountingholes_radius
  center: [0, 0, -mountingholes_depth / 2]
motor = motor.subtract(mountingholes.translate [mountingholes_fromcent, mountingholes_fromcent, 0] )
motor = motor.subtract(mountingholes.translate [-mountingholes_fromcent, mountingholes_fromcent, 0] )
motor = motor.subtract(mountingholes.translate [mountingholes_fromcent, -mountingholes_fromcent, 0] )
motor = motor.subtract(mountingholes.translate [-mountingholes_fromcent, -mountingholes_fromcent, 0] )

assembly.add (motor)

# at this point there should be four holes, but because translate() adjusts the
# mountingholes object, subsequent translate() operations move the hole out of range of 
# the motor body.
# This can be seen by making a new mountingholes object between subtract operations.
# This is a change from the (better) way it used to work.

**Comment by kaosat-dev** [comment]
Hello Derrick,

Actually , this change is on purpose: every operation (translate, rotate, scale, union, subtract, intersect), modifies the current object.
There was a relatively lengthy discussion on the logic behind it on Google+ a few months back here :https://plus.google.com/u/0/112899217323877236232/posts/D6uLT52z5U7

I can understand that it can be a bit disturbing at firtst, but I find it helps to view the 'Mountingholes' object in this case as an "real" object you move around to substract it from the casing : the object would not dissapear after a substraction, and would still be at the "last place you left it". 

Also since Coffeescad is object oriented , it would feel even weirder to have 
MyPart.translate([0,10,0]) not modify the original object (position is an attribute of the class, it should therefore modify it)

I am very sorry if this cause any inconvenience, this is once again due to the lack of up to date documentation, but that should be done very soon:)

So :
The way to do it now would be : 

motor = motor.subtract(mountingholes.clone().translate [mountingholes_fromcent, mountingholes_fromcent, 0] )
motor = motor.subtract(mountingholes.clone().translate [-mountingholes_fromcent, mountingholes_fromcent, 0] )
motor = motor.subtract(mountingholes.clone().translate [mountingholes_fromcent, -mountingholes_fromcent, 0] )
motor = motor.subtract(mountingholes.clone().translate [-mountingholes_fromcent, -mountingholes_fromcent, 0] )

or, more concise: 
for i in [-1,1]
  for j in [-1,1]
    motor.subtract(mountingholes.clone().translate [i_mountingholes_fromcent, j_mountingholes_fromcent, 0] )

Also you could replace this part 
motor = motorBody.union([ring, shaft])

With this:
motor = new CSGBase().union([motorBody, ring, shaft])
Less concise, but more accurate

**Comment by kaosat-dev** [comment]
Also, FYI , it would be best to pull the latest changes, I partially broke some translate() related stuff last night..
